pipeline {
    agent {
        label 'jenkins-agent1'
    }
    environment {
        DOCKER_HOST='tcp:docker.local:2375'
    }
    stages {
        stage('Build Docker agent Image') {
            steps {
                sh 'docker version'
            }
        }
    }
}