pipeline {
    agent {
        label 'jenkins-agent1'
    }
    stages {
        stage('Build Docker agent Image') {
            steps {
                sh 'dockerd &'
                sh 'service docker start'
                sh 'service docker status'
                sh 'docker version'
            }
        }
    }
}