pipeline {
    agent {
        docker {
        label 'jenkins-agent1'
        args '--network jenkins'
        }
    }
    environment {
        DOCKER_HOST='tcp://docker:2375'
    }
    stages {
        stage('Build Docker agent Image') {
            steps {
                sh 'docker version'
            }
        }
    }
}